### ISSUE TITLE
Formalize Python and OGGM installation and folder structure

### ISSUE THREAD

**Issue by JordiBolibar** [ODINN-SciML/ODINN#30]
We should clearly specify in the README how to and where to install Python, OGGM and PyCall. I'm not sure that these should go in this repo, but we could perhaps create a script to install everything in a correct relative path from this repo. At the very least, we should give a clear indication on what paths and folder structures are expected in order to correctly replicate what ODINN is expecting.

**Comment by JordiBolibar** [comment]
I have added a more detailed explanation with [this commit](https://github.com/ODINN-SciML/ODINN_toy/commit/efa3f46b4aa13dcf500ddc9b0be6c395c5a9d032). @facusapienza21 what do you think? Would you add anything else?

**Comment by facusapienza21** [comment]
@JordiBolibar, although the OGGM installation seems to be ok, `ODINN.jl` is still not working. The extra information is useful, but I will probably add more description once I make it work.

**Comment by JordiBolibar** [comment]
We should also document the Python installation dependencies, beyond OGGM.

**Comment by facusapienza21** [comment]
@JordiBolibar is that necessary? When you create the virtual environment for OGGM you also install all the necessary dependencies for Python.

**Comment by JordiBolibar** [comment]
Ah yes, right. With conda forge you get that. Then we should add at least add the dependency on `MBsandbox`.

**Comment by JordiBolibar** [comment]
In #46 I have expanded the guidelines in the README and completely restructured the folders to follow the package guidelines.
